# app/evidence/formatter.py
"""
Format evidence and source documents for display.
Ensures AI-generated content is visually distinguishable
from source data — a challenge requirement.
"""
from typing import Any, Optional
from datetime import datetime
import json


class EvidenceFormatter:
    """
    Formats evidence rows and source documents for the frontend.
    
    Key responsibility:
    - Mark what is SOURCE DATA vs AI-GENERATED
    - Add disclaimers for coded labels
    - Format for human readability
    """
    
    # Labels that come from dictionary tables, not clinical notes
    DICTIONARY_DERIVED_LABELS = {
        "d_labitems": "Lab item dictionary",
        "d_items": "Chart item dictionary",
        "d_icd_diagnoses": "ICD diagnosis dictionary",
        "d_icd_procedures": "ICD procedure dictionary",
    }
    
    def format_source_document(
        self, collection: str, doc: dict
    ) -> dict:
        """
        Format a source document for display.
        Adds metadata about what kind of data this is.
        """
        formatted = {
            "collection": collection,
            "data": doc,
            "metadata": self._get_metadata(collection, doc),
            "display_hints": self._get_display_hints(collection, doc),
        }
        
        return formatted
    
    def format_evidence_row(
        self,
        row: dict,
        source_trace: dict,
        is_ai_generated: bool = False,
    ) -> dict:
        """
        Format a single evidence row.
        Clearly marks AI-generated vs source data.
        """
        return {
            "data": row,
            "source_trace": source_trace,
            "content_type": "ai_generated" if is_ai_generated else "source_data",
            "visual_marker": "🤖 AI" if is_ai_generated else "🗂️ Source",
            "disclaimers": self._get_row_disclaimers(row, source_trace),
        }
    
    def format_answer_with_evidence(
        self,
        answer: str,
        evidence: list[dict],
        query: dict,
        supporting_rows: int,
        refused: bool,
    ) -> dict:
        """
        Format a complete QA answer with its evidence.
        This is the main response format for the query endpoint.
        """
        result = {
            "answer": {
                "text": answer,
                "content_type": "ai_generated",
                "visual_marker": "🤖 AI Answer",
                "warning": "This answer was generated by AI from verified data rows. Verify against source data.",
            },
            "evidence": {
                "rows": evidence,
                "count": supporting_rows,
                "content_type": "source_data",
                "visual_marker": "🗂️ Verified Source Data",
            },
            "query": {
                "generated_query": query,
                "content_type": "ai_generated",
                "visual_marker": "🤖 AI-Generated Query",
            },
            "verification": {
                "refused": refused,
                "gate_status": "ABSTAINED" if refused else "VERIFIED",
                "reason": "zero_supporting_rows" if refused else None,
            },
            "safety_notice": (
                "Research and educational prototype only. "
                "Not for clinical use. Do not use for diagnosis, "
                "treatment, triage, or emergency decisions."
            ),
        }
        
        return result
    
    def format_timeline_event(
        self, event: dict
    ) -> dict:
        """
        Format a timeline event for display.
        Marks labels from dictionary tables.
        """
        detail = event.get("detail", {})
        label_source = detail.get("label_source")
        
        formatted = {
            **event,
            "display": {
                "label_is_from_dictionary": label_source is not None,
                "dictionary_source": label_source,
                "is_not_clinical_note": True,
            },
        }
        
        if label_source:
            formatted["display"]["warning"] = (
                f"Label from {label_source} — this is NOT a clinician-authored note"
            )
        
        return formatted
    
    def format_group_with_evidence(
        self, group: dict
    ) -> dict:
        """
        Format an event group, showing that source traces
        are preserved even when events are collapsed.
        """
        return {
            **group,
            "display": {
                "is_collapsed": group.get("is_collapsed", True),
                "member_count": group.get("event_count", 0),
                "source_traces_preserved": len(group.get("member_source_traces", [])),
                "warning": (
                    f"{group.get('event_count', 0)} events collapsed. "
                    f"All {len(group.get('member_source_traces', []))} source traces preserved."
                ),
            },
        }
    
    def _get_metadata(self, collection: str, doc: dict) -> dict:
        """Get metadata about a source document."""
        metadata = {
            "collection": collection,
            "is_clinical_note": False,  # MIMIC-IV demo has NO notes
            "data_type": "structured_code" if collection in (
                "diagnoses_icd", "procedures_icd"
            ) else "measurement" if collection in (
                "labevents", "chartevents", "outputevents"
            ) else "administrative" if collection in (
                "admissions", "transfers", "icustays"
            ) else "dictionary" if collection.startswith("d_") else "other",
        }
        
        if collection in self.DICTIONARY_DERIVED_LABELS:
            metadata["label_source"] = self.DICTIONARY_DERIVED_LABELS[collection]
            metadata["label_disclaimer"] = (
                f"Labels from {self.DICTIONARY_DERIVED_LABELS[collection]} "
                "are NOT clinician-authored notes"
            )
        
        return metadata
    
    def _get_display_hints(self, collection: str, doc: dict) -> dict:
        """Get display hints for the frontend."""
        hints = {
            "show_source_trace": True,
            "show_uncertainty": False,
            "highlight_abnormal": False,
            "time_field": None,
        }
        
        # Time field
        for field in ["charttime", "admittime", "intime", "starttime"]:
            if field in doc and doc[field] is not None:
                hints["time_field"] = field
                break
        
        # Abnormal highlighting
        if collection == "labevents":
            flag = doc.get("flag")
            if flag and str(flag).strip():
                hints["highlight_abnormal"] = True
            valuenum = doc.get("valuenum")
            ref_lo = doc.get("ref_range_lower")
            ref_hi = doc.get("ref_range_upper")
            if all(v is not None for v in [valuenum, ref_lo, ref_hi]):
                try:
                    if float(valuenum) < float(ref_lo) or float(valuenum) > float(ref_hi):
                        hints["highlight_abnormal"] = True
                except (ValueError, TypeError):
                    pass
        
        # Uncertainty
        if collection == "labevents":
            if doc.get("valuenum") is None and doc.get("value") is not None:
                hints["show_uncertainty"] = True
                hints["uncertainty_reason"] = "non_numeric_value"
        
        return hints
    
    def _get_row_disclaimers(self, row: dict, source_trace: dict) -> list[str]:
        """Get applicable disclaimers for an evidence row."""
        disclaimers = []
        
        collection = source_trace.get("collection", "")
        
        # All data is structured, not clinical notes
        disclaimers.append(
            "This is structured hospital data, not a clinician-authored note"
        )
        
        # Dictionary-derived labels
        if collection in self.DICTIONARY_DERIVED_LABELS:
            disclaimers.append(
                f"Label from {self.DICTIONARY_DERIVED_LABELS[collection]}, "
                "not a clinical observation"
            )
        
        # ICD codes
        if collection == "diagnoses_icd":
            disclaimers.append(
                "ICD code is a billing classification, not a clinical diagnosis"
            )
        
        # Missing units
        if row.get("value") is not None and row.get("uom") is None:
            disclaimers.append("Value has no unit of measure — interpret with caution")
        
        # Non-numeric values
        if row.get("value") is not None and row.get("valuenum") is None:
            disclaimers.append("Value is non-numeric — original text preserved")
        
        return disclaimers